source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'FBSDKCoreKit'
pod 'Alamofire', '~> 2.0'
pod "SwiftSpinner"
pod 'FBSDKLoginKit', :podspec => 'https://gist.githubusercontent.com/nlutsenko/cf1775dcae07eca6be43/raw/58b919433be07b791dd1036249185b22ecc3de3f/FBSDKLoginKit.podspec'
pod 'ParseFacebookUtilsV4'
pod 'Parse'

