source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
pod 'FBSDKCoreKit'
pod 'Alamofire', '~> 2.0'
pod "SwiftSpinner"
pod 'FBSDKLoginKit'
pod 'ParseFacebookUtilsV4'
pod 'Parse', '~>1.11.0'
pod 'Bolts'
pod 'ParseTwitterUtils'
pod 'Stripe'
pod 'QRCodeKit'
